[package]
name = "gm_binpkg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pelite = "0.9.0"
anyhow = "1.0.42"

log = "0.4.14"
simplelog = "0.10.0"