[package]
name = "gm_binpkg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pelite = "0.9.0"

# cli
clap = "3.0.0-beta.4"

colored = "2.0.0"

cc = "1.0.69" # Compiling C++, Using windows tools

cmake = "0.1.45"